Exception ignored in: <function _releaseLock at 0x71a9d9a559e0>
Traceback (most recent call last):
  File "/home/tzikos/anaconda3/envs/KUThesis/lib/python3.12/logging/__init__.py", line 243, in _releaseLock
    def _releaseLock():
  File "/home/tzikos/.vscode/extensions/ms-python.debugpy-2024.6.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch_regular.py", line 326, in __call__
    def __call__(self, frame, event, arg):
KeyboardInterrupt: